# Generated by Django 5.1.2 on 2024-10-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_vocabulary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabulary',
            old_name='word',
            new_name='phrase',
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='translate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
